name: '新しい記事のエントリー'
description: 'Issue を作ることで新しい記事のエントリーをすることができます。'
labels: ['article']
body:
  - type: 'markdown'
    attributes:
      value: |
        ## [Vim駅伝](https://vim-jp.org/ekiden/)とは

        - リレー形式で記事をリンクする営み
            - 既定の日付枠にURLを載せるだけ
        - 誰でも参加OK
            - 要: GitHubのアカウント
            - 著者名は設定可能
        - 季節ごとに投稿数ランキングが集計される

        [詳細](https://vim-jp.org/ekiden/about/)

        ## どんなものを書けば良いの？

        - Vimまたはテクノロジーに関連した内容
            - ノウハウ, 気づき
            - プラグイン紹介
            - 他のテキストエディタの話
            - Vimの二次創作の話
            - 開発の苦労話
            - etc.
        - 分量は自由
            - ほんの1文
            - 1万文字を超える大作
                - 長くなる場合はシリーズ化すると読み手に優しいかも
        - インターネット上で閲覧可能な場所に公開する
            - 技術記事の投稿サービス
            - 自前のブログ
            - スニペットサービス
            - etc.
        - 公開タイミングはできるだけ当日の午前中

        ## 参加方法

        - [スケジュール](https://vim-jp.org/ekiden/)のうち、「募集中」となっている日付から「参加する」
        - GitHubのフォーマットに従ってIssueを作成
            - Issueタイトルに公開年月日を記入
            - タイトルと注意事項への同意が必要
                - タイトルは公開日までに正式なものに書き換えればOK
            - 公開予定がすでに決まっている場合はその記事のURL
                - こちらも公開日までに正式なものに書き換えればOK
        - Issueを作ると、トップページに反映される
            - あとから決まった内容はIssueを編集すれば反映される
                - 内容のフォーマットを崩さないように注意
        - 参加キャンセルする際はIssueを `Close as not planned` でCloseする
        - 記事が公開された場合は、当日にIssueが自動でCloseされる

        ## 注意事項

        - 個人攻撃や差別的な内容を含む記事、公序良俗に反する不適切な記事は禁止
        - 明らかに不適切と判断された記事はリンクを削除する
            - GitHub経由での事前通告する

  - type: 'input'
    id: 'title'
    attributes:
      label: '記事タイトル'
      description: |
        Markdown に解釈される文字を使う場合は、タイトル全体を好きな数の `` ` `` で囲んでください。
        掲載時には先頭と末尾の `` ` `` とスペースは取り除かれます。
        後から変更することも可能です。
    validations:
      required: true
  - type: 'input'
    id: 'name'
    attributes:
      label: '執筆者名'
      description: |
        省略した場合は GitHub のユーザー名になります。
  - type: 'input'
    id: 'url'
    attributes:
      label: '記事 URL'
      description: |
        公開先のURLです。
        後から変更することも可能です。

  - type: 'checkboxes'
    attributes:
      label: 注意事項の確認
      description: 前述の注意事項を確認してください
      options:
        - label: 不適切な内容を投稿しません
          required: true
