on:
  pull_request:
    paths:
      - ".github/**/*.yml"
      - ".github/**/*.yaml"

permissions:
  pull-requests: write

jobs:
  pinact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Check GitHub Actions with pinact
        uses: suzuki-shunsuke/pinact-action@cf51507d80d4d6522a07348e3d58790290eaf0b6 # v2.0.0
        with:
          skip_push: "true"
