name: Check format and test build
'on':
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Run ESLint
        run: pnpm lint:check
      - name: Run Prettier
        run: pnpm prettier:check
      - name: Run Astro Check
        run: pnpm astro:check
      - name: Run test
        run: pnpm test
      - name: Run Build
        run: pnpm build
